/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParentLeaderboardRouteImport } from './routes/parent/leaderboard'
import { Route as ParentDashboardRouteImport } from './routes/parent/dashboard'
import { Route as ChildTriviaRouteImport } from './routes/child/trivia'
import { Route as ChildDuelRouteImport } from './routes/child/duel'
import { Route as ChildHomeRouteImport } from './routes/child/home'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthAcceptInviteRouteImport } from './routes/auth/accept-invite'
import { Route as ChallengeCodeRouteImport } from './routes/challenge/$code'
import { Route as ParentTriviaIndexRouteImport } from './routes/parent/trivia/index'
import { Route as ParentTriviaChallengeRouteImport } from './routes/parent/trivia/challenge'
import { Route as ParentChildrenNewRouteImport } from './routes/parent/children/new'
import { Route as ParentTriviaDuelChildIdRouteImport } from './routes/parent/trivia/duel.$childId'
import { Route as ParentChildrenChildIdStatsRouteImport } from './routes/parent/children/$childId/stats'
import { Route as ChildModuleModuleIdLevelsRouteImport } from './routes/child/module/$moduleId/levels'
import { Route as ChildModuleModuleIdLevelLevelIdResultRouteImport } from './routes/child/module/$moduleId/level/$levelId/result'
import { Route as ChildModuleModuleIdLevelLevelIdPlayRouteImport } from './routes/child/module/$moduleId/level/$levelId/play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentLeaderboardRoute = ParentLeaderboardRouteImport.update({
  id: '/parent/leaderboard',
  path: '/parent/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentDashboardRoute = ParentDashboardRouteImport.update({
  id: '/parent/dashboard',
  path: '/parent/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildTriviaRoute = ChildTriviaRouteImport.update({
  id: '/child/trivia',
  path: '/child/trivia',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildDuelRoute = ChildDuelRouteImport.update({
  id: '/child/duel',
  path: '/child/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildHomeRoute = ChildHomeRouteImport.update({
  id: '/child/home',
  path: '/child/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptInviteRoute = AuthAcceptInviteRouteImport.update({
  id: '/auth/accept-invite',
  path: '/auth/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeCodeRoute = ChallengeCodeRouteImport.update({
  id: '/challenge/$code',
  path: '/challenge/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentTriviaIndexRoute = ParentTriviaIndexRouteImport.update({
  id: '/parent/trivia/',
  path: '/parent/trivia/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentTriviaChallengeRoute = ParentTriviaChallengeRouteImport.update({
  id: '/parent/trivia/challenge',
  path: '/parent/trivia/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentChildrenNewRoute = ParentChildrenNewRouteImport.update({
  id: '/parent/children/new',
  path: '/parent/children/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentTriviaDuelChildIdRoute = ParentTriviaDuelChildIdRouteImport.update({
  id: '/parent/trivia/duel/$childId',
  path: '/parent/trivia/duel/$childId',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentChildrenChildIdStatsRoute =
  ParentChildrenChildIdStatsRouteImport.update({
    id: '/parent/children/$childId/stats',
    path: '/parent/children/$childId/stats',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChildModuleModuleIdLevelsRoute =
  ChildModuleModuleIdLevelsRouteImport.update({
    id: '/child/module/$moduleId/levels',
    path: '/child/module/$moduleId/levels',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChildModuleModuleIdLevelLevelIdResultRoute =
  ChildModuleModuleIdLevelLevelIdResultRouteImport.update({
    id: '/child/module/$moduleId/level/$levelId/result',
    path: '/child/module/$moduleId/level/$levelId/result',
    getParentRoute: () => rootRouteImport,
  } as any)
const ChildModuleModuleIdLevelLevelIdPlayRoute =
  ChildModuleModuleIdLevelLevelIdPlayRouteImport.update({
    id: '/child/module/$moduleId/level/$levelId/play',
    path: '/child/module/$moduleId/level/$levelId/play',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/challenge/$code': typeof ChallengeCodeRoute
  '/child/home': typeof ChildHomeRoute
  '/child/trivia': typeof ChildTriviaRoute
  '/child/duel': typeof ChildDuelRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/leaderboard': typeof ParentLeaderboardRoute
  '/parent/children/new': typeof ParentChildrenNewRoute
  '/parent/trivia/challenge': typeof ParentTriviaChallengeRoute
  '/parent/trivia/': typeof ParentTriviaIndexRoute
  '/child/module/$moduleId/levels': typeof ChildModuleModuleIdLevelsRoute
  '/parent/children/$childId/stats': typeof ParentChildrenChildIdStatsRoute
  '/parent/trivia/duel/$childId': typeof ParentTriviaDuelChildIdRoute
  '/child/module/$moduleId/level/$levelId/play': typeof ChildModuleModuleIdLevelLevelIdPlayRoute
  '/child/module/$moduleId/level/$levelId/result': typeof ChildModuleModuleIdLevelLevelIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/challenge/$code': typeof ChallengeCodeRoute
  '/child/home': typeof ChildHomeRoute
  '/child/trivia': typeof ChildTriviaRoute
  '/child/duel': typeof ChildDuelRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/leaderboard': typeof ParentLeaderboardRoute
  '/parent/children/new': typeof ParentChildrenNewRoute
  '/parent/trivia/challenge': typeof ParentTriviaChallengeRoute
  '/parent/trivia': typeof ParentTriviaIndexRoute
  '/child/module/$moduleId/levels': typeof ChildModuleModuleIdLevelsRoute
  '/parent/children/$childId/stats': typeof ParentChildrenChildIdStatsRoute
  '/parent/trivia/duel/$childId': typeof ParentTriviaDuelChildIdRoute
  '/child/module/$moduleId/level/$levelId/play': typeof ChildModuleModuleIdLevelLevelIdPlayRoute
  '/child/module/$moduleId/level/$levelId/result': typeof ChildModuleModuleIdLevelLevelIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/accept-invite': typeof AuthAcceptInviteRoute
  '/challenge/$code': typeof ChallengeCodeRoute
  '/child/home': typeof ChildHomeRoute
  '/child/trivia': typeof ChildTriviaRoute
  '/child/duel': typeof ChildDuelRoute
  '/parent/dashboard': typeof ParentDashboardRoute
  '/parent/leaderboard': typeof ParentLeaderboardRoute
  '/parent/children/new': typeof ParentChildrenNewRoute
  '/parent/trivia/challenge': typeof ParentTriviaChallengeRoute
  '/parent/trivia/': typeof ParentTriviaIndexRoute
  '/child/module/$moduleId/levels': typeof ChildModuleModuleIdLevelsRoute
  '/parent/children/$childId/stats': typeof ParentChildrenChildIdStatsRoute
  '/parent/trivia/duel/$childId': typeof ParentTriviaDuelChildIdRoute
  '/child/module/$moduleId/level/$levelId/play': typeof ChildModuleModuleIdLevelLevelIdPlayRoute
  '/child/module/$moduleId/level/$levelId/result': typeof ChildModuleModuleIdLevelLevelIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/auth/accept-invite'
    | '/challenge/$code'
    | '/child/home'
    | '/child/trivia'
    | '/child/duel'
    | '/parent/dashboard'
    | '/parent/leaderboard'
    | '/parent/children/new'
    | '/parent/trivia/challenge'
    | '/parent/trivia/'
    | '/child/module/$moduleId/levels'
    | '/parent/children/$childId/stats'
    | '/parent/trivia/duel/$childId'
    | '/child/module/$moduleId/level/$levelId/play'
    | '/child/module/$moduleId/level/$levelId/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/auth/accept-invite'
    | '/challenge/$code'
    | '/child/home'
    | '/child/trivia'
    | '/child/duel'
    | '/parent/dashboard'
    | '/parent/leaderboard'
    | '/parent/children/new'
    | '/parent/trivia/challenge'
    | '/parent/trivia'
    | '/child/module/$moduleId/levels'
    | '/parent/children/$childId/stats'
    | '/parent/trivia/duel/$childId'
    | '/child/module/$moduleId/level/$levelId/play'
    | '/child/module/$moduleId/level/$levelId/result'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/auth/accept-invite'
    | '/challenge/$code'
    | '/child/home'
    | '/child/trivia'
    | '/child/duel'
    | '/parent/dashboard'
    | '/parent/leaderboard'
    | '/parent/children/new'
    | '/parent/trivia/challenge'
    | '/parent/trivia/'
    | '/child/module/$moduleId/levels'
    | '/parent/children/$childId/stats'
    | '/parent/trivia/duel/$childId'
    | '/child/module/$moduleId/level/$levelId/play'
    | '/child/module/$moduleId/level/$levelId/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthAcceptInviteRoute: typeof AuthAcceptInviteRoute
  ChallengeCodeRoute: typeof ChallengeCodeRoute
  ChildHomeRoute: typeof ChildHomeRoute
  ChildTriviaRoute: typeof ChildTriviaRoute
  ChildDuelRoute: typeof ChildDuelRoute
  ParentDashboardRoute: typeof ParentDashboardRoute
  ParentLeaderboardRoute: typeof ParentLeaderboardRoute
  ParentChildrenNewRoute: typeof ParentChildrenNewRoute
  ParentTriviaChallengeRoute: typeof ParentTriviaChallengeRoute
  ParentTriviaIndexRoute: typeof ParentTriviaIndexRoute
  ChildModuleModuleIdLevelsRoute: typeof ChildModuleModuleIdLevelsRoute
  ParentChildrenChildIdStatsRoute: typeof ParentChildrenChildIdStatsRoute
  ParentTriviaDuelChildIdRoute: typeof ParentTriviaDuelChildIdRoute
  ChildModuleModuleIdLevelLevelIdPlayRoute: typeof ChildModuleModuleIdLevelLevelIdPlayRoute
  ChildModuleModuleIdLevelLevelIdResultRoute: typeof ChildModuleModuleIdLevelLevelIdResultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/leaderboard': {
      id: '/parent/leaderboard'
      path: '/parent/leaderboard'
      fullPath: '/parent/leaderboard'
      preLoaderRoute: typeof ParentLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/dashboard': {
      id: '/parent/dashboard'
      path: '/parent/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof ParentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/trivia': {
      id: '/child/trivia'
      path: '/child/trivia'
      fullPath: '/child/trivia'
      preLoaderRoute: typeof ChildTriviaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/home': {
      id: '/child/home'
      path: '/child/home'
      fullPath: '/child/home'
      preLoaderRoute: typeof ChildHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/trivia/': {
      id: '/parent/trivia/'
      path: '/parent/trivia'
      fullPath: '/parent/trivia/'
      preLoaderRoute: typeof ParentTriviaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/trivia/challenge': {
      id: '/parent/trivia/challenge'
      path: '/parent/trivia/challenge'
      fullPath: '/parent/trivia/challenge'
      preLoaderRoute: typeof ParentTriviaChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/children/new': {
      id: '/parent/children/new'
      path: '/parent/children/new'
      fullPath: '/parent/children/new'
      preLoaderRoute: typeof ParentChildrenNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/trivia/duel/$childId': {
      id: '/parent/trivia/duel/$childId'
      path: '/parent/trivia/duel/$childId'
      fullPath: '/parent/trivia/duel/$childId'
      preLoaderRoute: typeof ParentTriviaDuelChildIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/children/$childId/stats': {
      id: '/parent/children/$childId/stats'
      path: '/parent/children/$childId/stats'
      fullPath: '/parent/children/$childId/stats'
      preLoaderRoute: typeof ParentChildrenChildIdStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/module/$moduleId/levels': {
      id: '/child/module/$moduleId/levels'
      path: '/child/module/$moduleId/levels'
      fullPath: '/child/module/$moduleId/levels'
      preLoaderRoute: typeof ChildModuleModuleIdLevelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/module/$moduleId/level/$levelId/result': {
      id: '/child/module/$moduleId/level/$levelId/result'
      path: '/child/module/$moduleId/level/$levelId/result'
      fullPath: '/child/module/$moduleId/level/$levelId/result'
      preLoaderRoute: typeof ChildModuleModuleIdLevelLevelIdResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/module/$moduleId/level/$levelId/play': {
      id: '/child/module/$moduleId/level/$levelId/play'
      path: '/child/module/$moduleId/level/$levelId/play'
      fullPath: '/child/module/$moduleId/level/$levelId/play'
      preLoaderRoute: typeof ChildModuleModuleIdLevelLevelIdPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/child/duel': {
      id: '/child/duel'
      path: '/child/duel'
      fullPath: '/child/duel'
      preLoaderRoute: typeof ChildDuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/accept-invite': {
      id: '/auth/accept-invite'
      path: '/auth/accept-invite'
      fullPath: '/auth/accept-invite'
      preLoaderRoute: typeof AuthAcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/$code': {
      id: '/challenge/$code'
      path: '/challenge/$code'
      fullPath: '/challenge/$code'
      preLoaderRoute: typeof ChallengeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthAcceptInviteRoute: AuthAcceptInviteRoute,
  ChallengeCodeRoute: ChallengeCodeRoute,
  ChildHomeRoute: ChildHomeRoute,
  ChildTriviaRoute: ChildTriviaRoute,
  ChildDuelRoute: ChildDuelRoute,
  ParentDashboardRoute: ParentDashboardRoute,
  ParentLeaderboardRoute: ParentLeaderboardRoute,
  ParentChildrenNewRoute: ParentChildrenNewRoute,
  ParentTriviaChallengeRoute: ParentTriviaChallengeRoute,
  ParentTriviaIndexRoute: ParentTriviaIndexRoute,
  ChildModuleModuleIdLevelsRoute: ChildModuleModuleIdLevelsRoute,
  ParentChildrenChildIdStatsRoute: ParentChildrenChildIdStatsRoute,
  ParentTriviaDuelChildIdRoute: ParentTriviaDuelChildIdRoute,
  ChildModuleModuleIdLevelLevelIdPlayRoute:
    ChildModuleModuleIdLevelLevelIdPlayRoute,
  ChildModuleModuleIdLevelLevelIdResultRoute:
    ChildModuleModuleIdLevelLevelIdResultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
